### ISSUE TITLE
Confirm mining has been removed/disabled

### ISSUE THREAD

**Issue by tedepstein** [joshfarrant/slack-clicky#16]
There are still some open comment threads in [reviews here](https://chrome.google.com/webstore/detail/clicky-for-slack/bllgmdlgbbmijcoecbnmgeoekhebgmac/reviews) on the Chrome Web Store, referring to cryptocurrency mining. It appears you have removed mining in commits e58c339bf9162f4ec3d5024bce9b04f5deb7a565 and f041b1472091fdef8b3c3c088c5653b44cdb2bbe. 

Can you confirm that mining is now fully disabled, and that you won't be adding it back without a high-visibility notification to new and existing users? 

You might want to close the loop on those reviews, as some potential users may get the impression that Clicky is still mining in the background, and decide to look elsewhere for a solution.

**Comment by joshfarrant** [comment]
Mining has been removed, yes, and I have no plans to add it back in. I am, however, still considering offering a paid tier (for a very small one-off fee) to unlock 'pro' features, such as multiple team support and theming.

I do my best to respond to all comments, questions, and reviews on the Chrome Store. As far as I'm aware there are no comments that have gone unanswered.
