### ISSUE TITLE
Feature: Pick up Starred Groups|Users|Chats

### ISSUE THREAD

**Issue by wwb** [joshfarrant/slack-clicky#7]
I'm in a ton of slack groups within our org and such and I use the starring feature heavily. It would be cool if #clicky pulled those groups in and put them in the top of the list like the typical slack client does, making it easy to share things to the people I share things with most.

Thanks for making a handy plugin!

**Comment by joshfarrant** [comment]
Interesting idea, thanks for the feedback. Definitely something I'll consider adding in a future release :smile:.

**Comment by joshfarrant** [comment]
Closing this for now as it doesn't appear that you're able to star channels/groups/anything in Slack currently.

**Comment by wwb** [comment]
First no issue with the close -- if I cared that much I should probably submit a PR :)

That said I'm a bit shocked by the assertion you can't star things in slack. Your comment might be in reference to the API which I can't claim to have reviewed, but at least in the thick and web clients you can star just about any entity -- be it a channel, a user, a chat or even an individual post.

**Comment by joshfarrant** [comment]
Ok great, upon further inspection it looks like the `is_starred` property isn't returned by Slack's API unless it's set to `true` (annoyingly inconsistent with everything else in their API, but there you go), which explains why I'd not seen it before.

Shouldn't be a problem then, I'll implement a _Starred_ section which can be enabled from the Settings page. :+1:
